---

#|  Add systemd configuration files

- name: config - Ensure systemd directories exist
  file:
    state: directory
    path: "{{ item }}"
    recurse: yes
  with_items:
    - "{{ systemd_default_dir }}"
    - "{{ systemd_unit_dir }}"

- name: config - Ensure override directories exist
  file:
    state: directory
    path: "{{ systemd_unit_dir }}/{{ item.Service_Name }}.d"
    recurse: yes
  with_items:
    - "{{ systemd_service_overrides }}"
  when: item not in systemd_remove_service_overrides

- name: config - Add default environment vars
  template:
    src: default.j2
    dest: "{{ systemd_default_dir }}/{{ item.Service_Name }}"
  with_items:
    - "{{ systemd_environment_vars }}"  
  when: item not in systemd_remove_environment_vars
  register: env_file

# - debug:
#     msg: "{{ item.Service_Name }}"
#   with_items: "{{ systemd_services }}"

- name: config - Add systemd unit files
  template:
    src: service.j2
    dest: "{{ systemd_unit_dir }}/{{ item.Service_Name }}.service"
  with_items:
    - "{{ systemd_services }}"    
  when: item not in systemd_remove_services
  register: unit_file

- name: config - Add systemd override files
  template:
    src: override.conf.j2
    dest: "{{ systemd_unit_dir }}/{{ item.Service_Name }}.d/override.conf"
  with_items:
    - "{{ systemd_service_overrides }}"  
  when: item not in systemd_remove_service_overrides
  register: override_file

- name: config - Reload systemctl daemon configuration
  shell: systemctl daemon-reload
  when: env_file.changed or unit_file.changed or override_file.changed
